### PR TITLE
Force address resolution if the broker epoch changes

### LINKED ISSUE #2944: Kafka consumer (v1.4.2) gets stuck (NOT_COORDINATOR) whilst rejoining a group after a broker rolling update
Hi,

First off, my company is a long-time user of rdkafka, thanks for all the work!

tl;dr We've had consumers stall indefinitely after rolling update of Kafka brokers with "not coordinator" errors returned to JoinGroup requests. The issue is present in 1.4.0 and 1.4.2 but not in 1.2.0 and happens fairly often after a rollout. This seems similar to  #2791 but that should have been fixed in 1.4.2 according to that thread. Further, we've tried not subscribing to rebalance events without any difference. The issue may be related to autocommits. This looks similar to #2933, too; however, there the reporter says the issue does not exist in 1.4.0 whilst for us it does, as far as we can tell, and also there's no SESSTMOUT reported in their logs.

Description
===========

### Background:
We use the Go and Python bindings for rdkafka; we build these ourselves, including rdkafka which we compile against `musl` . The Python and Go configuration we have is almost identical with the main exception that in Go we use `enable.auto.commit` and make calls to `StoreOffsets` whilst in Python we call `consumer.commit()` (in either case, the goal is at-least-once delivery to the business code). 
I mention this because this issue seems to have never been detected in our Python consumers whilst it frequently happens to the Go ones (we do have more Go consumers, however). In Go, we periodically use Poll(), just like in Python.

We perform rolling updates of our 3 Kafka brokers fairly regularly. The whole rollout takes about 12-13 minutes -- ~30s to shutdown, ~30s to attach the persistent volume to the new instance (a Kubernetes pod), 180s grace period before moving on to the next one. (This process could be improved to be signal-based and to be mindful of the current controller :) ). 

### The Issue: 

With rdkafka 1.2, we can see the brokers handing over the coordinator role and the clients rejoining the consumer groups -- sometimes there's temporarily NOT_COORDINATOR responses which can be expected during the rollout. Here is an example of the broker JoinGroup responses during a rolling update:

rdkafka-1 2-normal

Here's the same rollout but on an environment with rdkafka 1.4 clients:
rdkafka-1 4 2-issue

Note the pre-existing "NOT COORDINATOR" errors already present and how these persist long after the 3 JoinGroup successful responses peaks (matching the 3 brokers getting replaced). These errors persist until the consumers which are stuck get restarted. The way we identify the stuck consumers is by having a goroutine reporting the length of `consumer.Assignment()` and if that is `0` for a prolonged period of time (this is adjusted for other factors that could lead to 0 assignment, ofc). In the logs of these affected consumers, there's always a

`%4\|1593263797.864\|SESSTMOUT\|rdkafka#consumer-1\| [thrd:main]: Consumer group session timed out (in join-state started) after 10488 ms without a successful response from the group coordinator (broker 0, last error was Broker: Not coordinator): revoking assignment and rejoining group` or a variation of this with `last error was Success`

The issue (which I assume starts with SESSTMOUT ) seems to happen a bit after the last broker has been replaced. It _seems_ that the NOT_COORDINATOR is always / most of the time returned by the first broker that has been replaced during the rollout. To me, it seems that the consumer still thinks the coordinator is that broker , missing the fact that the last broker to be replaced has successfully rejoined the cluster and became the group coordinator in the meantime. However, this may just be heavily correlated due the constant speed at which the rollout happens and how that interacts with some consumer timeout parameters.

Of course, SESSTMOUT alone isn't the issue as long as rdkafka recovers from it. Our rdkafka 1.4 Python consumers do recover from it, it seems, which is why we've been suspicious of: our Go code, the `confluent-kafka-go`, and rdkafka. We've ruled out the first two and confirmed it's the latter one by reverting to 1.2 where the issue disappeared.

How to reproduce
================
Have an idle consumer (single consumer in a CG is enough), then trigger a rolling update.
What we have noticed is that the issue does not occur if this consumer does not have any offsets stored (i.e all offsets are -1001) ; otherwise, the consumer can get stuck after a broker rolling update. This is why I am suspricious of autocommit with StoreOffsets versus explicitly calling commit()

### We've ruled out the following:
- given we weren't seeing the issue in Python, we considered the `confluent-kafka-go` wrapper. However, rolling it back to 1.1 (whilst still building it against rdkafka 1.4) did not make a difference
- in the past we had observed some surprising behaviour with rebalance events so we tried disabling `go.application.rebalance.enable` and either a pass a `nil` callback or a rebalanceCb function when calling Go's `consumer.Subscribe()`. In all cases, this did not make a difference
- slowing down the broker rollout (from 180s to 240s pause) made no difference. 
- setting `topic.metadata.refresh.interval.ms` to something like 150s did not make a difference (as expected, as that shouldn't be necessary).
- tested with Kafka 2.1 brokers -- no change, (although we stopped seeing but no longer saw "MEMBER_ID_REQUIRED" and "UNKNOWN_MEMBER_ID" errors returned -- I assume the protocol is now such that if we don't use Static group membership, the brokers respond with this message, then rdkafka generates an ID and succeeds).

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.4.0`, `1.4.2`
 - [x] Apache Kafka version: `2.4.1` (with `log.message.format.version=2.1`)
 - [x] librdkafka client configuration: 

Python (no issue observed):
```
'default.topic.config': {
    'auto.offset.reset': 'earliest'
},
'metadata.request.timeout.ms': 20000,
'enable.auto.commit': False,
'api.version.request': True,
'fetch.wait.max.ms': 100,
'log.connection.close': False,
'max.partition.fetch.bytes': MEBIBYTE * 5,
'statistics.interval.ms': 15000,
'queued.max.messages.kbytes': 1024 * 64,

```
Go (issue observed):
```
"auto.offset.reset":           "earliest",
"enable.auto.commit":          true,
"enable.auto.offset.store":    false,
"metadata.request.timeout.ms": 20000,
"auto.commit.interval.ms":     2000,
"log.connection.close":        false,
"max.poll.interval.ms":        300000,
"max.partition.fetch.bytes":   int(units.Mebibyte * 5),
"queued.max.messages.kbytes": 1024 * 64,
"go.application.rebalance.enable": true,

```

 - [x] Operating system: `alpine linux container`, kernel: `4.14.165`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka:
Using `debug=consumer,cgrp,topic,metadata` for a consumer that has StoredOffsets, starting right before a rolling update starts.
Below is an excerpt , here's a full gist (3.5k lines) https://gist.github.com/dimpavloff/f7c8ee9975eb96b1bfe89ec385d78178  

<details>

```
%7|1592857801.772|HEARTBEAT|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/0: Heartbeat for group "infrastructure.postmerge_tests.kafka.testconsumer" generation id 11
%7|1592857802.697|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op GET_ASSIGNMENT (v0) in state up (join state started, v4 vs 0)
%7|1592857802.734|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [0]: stored offset 3, committed offset 3: not including in commit
%7|1592857802.734|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [1]: stored offset 3, committed offset 3: not including in commit
%7|1592857802.734|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [2]: stored offset 3, committed offset 3: not including in commit
%7|1592857802.734|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [3]: stored offset 3, committed offset 3: not including in commit
%7|1592857802.734|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [4]: stored offset 3, committed offset 3: not including in commit
%7|1592857802.734|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [5]: stored offset 3, committed offset 3: not including in commit
%7|1592857802.734|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [6]: stored offset 6, committed offset 6: not including in commit
%7|1592857802.734|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [7]: stored offset -1001, committed offset -1001: not including in commit
%7|1592857802.734|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [8]: stored offset 3, committed offset 3: not including in commit
%7|1592857802.734|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [9]: stored offset 3, committed offset 3: not including in commit
%7|1592857802.734|COMMIT|rdkafka#consumer-1| [thrd:main]: OffsetCommit for 10 partition(s): cgrp auto commit timer: returned: Local: No offset stored

...

%7|1592858026.776|HEARTBEAT|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/0: Heartbeat for group "infrastructure.postmerge_tests.kafka.testconsumer" generation id 11
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]: 10.137.8.12:9094/0: ===== Received metadata (for 1 requested topics): broker down =====
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]: 10.137.8.12:9094/0: ClusterId: 9GR7XMKHSVOWc2aa3DQDUQ, ControllerId: 0
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]: 10.137.8.12:9094/0: 3 brokers, 1 topics
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]: 10.137.8.12:9094/0:   Broker #0/3: 10.137.8.12:9094 NodeId 0
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]: 10.137.8.12:9094/0:   Broker #1/3: 10.137.70.154:9094 NodeId 2
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]: 10.137.8.12:9094/0:   Broker #2/3: 10.137.150.246:9094 NodeId 1
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]: 10.137.8.12:9094/0:   Topic #0/1: infrastructure.postmerge_tests.kafka.testconsumer with 10 partitions
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]:   Topic infrastructure.postmerge_tests.kafka.testconsumer partition 0 Leader 2
%7|1592858026.815|TOPICUPD|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [0]: migrating from broker 1 to 2 (leader is 2): leader updated
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [0]: delegate to broker 10.137.70.154:9094/2 (rktp 0x261ee60, term 0, ref 5)
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [0]: no longer delegated to broker 10.137.150.246:9094/1
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [0]: delegating to broker 10.137.70.154:9094/2 for partition with 0 messages (0 bytes) queued
%7|1592858026.815|BRKMIGR|rdkafka#consumer-1| [thrd:main]: Migrating topic infrastructure.postmerge_tests.kafka.testconsumer [0] 0x261ee60 from 10.137.150.246:9094/1 to 10.137.70.154:9094/2 (sending PARTITION_LEAVE to 10.137.150.246:9094/1)
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]:   Topic infrastructure.postmerge_tests.kafka.testconsumer partition 1 Leader 0
%7|1592858026.815|TOPICUPD|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [1]: migrating from broker 1 to 0 (leader is 0): leader updated
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [1]: delegate to broker 10.137.8.12:9094/0 (rktp 0x261f260, term 0, ref 5)
%7|1592858026.815|FETCHADD|rdkafka#consumer-1| [thrd:10.137.148.17:9094/1]: 10.137.150.246:9094/1: Removed infrastructure.postmerge_tests.kafka.testconsumer [0] from fetch list (4 entries, opv 2): forced removal
%7|1592858026.815|TOPBRK|rdkafka#consumer-1| [thrd:10.137.148.17:9094/1]: 10.137.150.246:9094/1: Topic infrastructure.postmerge_tests.kafka.testconsumer [0]: leaving broker (0 messages in xmitq, next broker 10.137.70.154:9094/2, rktp 0x261ee60)
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [1]: no longer delegated to broker 10.137.150.246:9094/1
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [1]: delegating to broker 10.137.8.12:9094/0 for partition with 0 messages (0 bytes) queued
%7|1592858026.815|BRKMIGR|rdkafka#consumer-1| [thrd:main]: Migrating topic infrastructure.postmerge_tests.kafka.testconsumer [1] 0x261f260 from 10.137.150.246:9094/1 to 10.137.8.12:9094/0 (sending PARTITION_LEAVE to 10.137.150.246:9094/1)
%7|1592858026.815|TOPBRK|rdkafka#consumer-1| [thrd:10.137.91.181:9094/2]: 10.137.70.154:9094/2: Topic infrastructure.postmerge_tests.kafka.testconsumer [0]: joining broker (rktp 0x261ee60, 0 message(s) queued)
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]:   Topic infrastructure.postmerge_tests.kafka.testconsumer partition 2 Leader 0
%7|1592858026.815|FETCHADD|rdkafka#consumer-1| [thrd:10.137.91.181:9094/2]: 10.137.70.154:9094/2: Added infrastructure.postmerge_tests.kafka.testconsumer [0] to fetch list (1 entries, opv 2, 0 messages queued): fetchable
%7|1592858026.815|FETCHADD|rdkafka#consumer-1| [thrd:10.137.148.17:9094/1]: 10.137.150.246:9094/1: Removed infrastructure.postmerge_tests.kafka.testconsumer [1] from fetch list (3 entries, opv 2): forced removal
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]:   Topic infrastructure.postmerge_tests.kafka.testconsumer partition 3 Leader 2
%7|1592858026.815|TOPBRK|rdkafka#consumer-1| [thrd:10.137.148.17:9094/1]: 10.137.150.246:9094/1: Topic infrastructure.postmerge_tests.kafka.testconsumer [1]: leaving broker (0 messages in xmitq, next broker 10.137.8.12:9094/0, rktp 0x261f260)
%7|1592858026.815|TOPICUPD|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [3]: migrating from broker 0 to 2 (leader is 2): leader updated
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [3]: delegate to broker 10.137.70.154:9094/2 (rktp 0x2622400, term 0, ref 6)
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [3]: no longer delegated to broker 10.137.8.12:9094/0
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [3]: delegating to broker 10.137.70.154:9094/2 for partition with 0 messages (0 bytes) queued
%7|1592858026.815|BRKMIGR|rdkafka#consumer-1| [thrd:main]: Migrating topic infrastructure.postmerge_tests.kafka.testconsumer [3] 0x2622400 from 10.137.8.12:9094/0 to 10.137.70.154:9094/2 (sending PARTITION_LEAVE to 10.137.8.12:9094/0)
%7|1592858026.815|METADATA|rdkafka#consumer-1| [thrd:main]:   Topic infrastructure.postmerge_tests.kafka.testconsumer partition 4 Leader 2
%7|1592858026.815|TOPICUPD|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [4]: migrating from broker 1 to 2 (leader is 2): leader updated
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [4]: delegate to broker 10.137.70.154:9094/2 (rktp 0x2622800, term 0, ref 5)
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [4]: no longer delegated to broker 10.137.150.246:9094/1
%7|1592858026.815|BRKDELGT|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [4]: delegating to broker 10.137.70.154:9094/2 for partition with 0 messages (0 bytes) queued
%7|1592858026.815|TOPBRK|rdkafka#consumer-1| [thrd:10.137.13.66:9094/0]: 10.137.8.12:9094/0: Topic infrastructure.postmerge_tests.kafka.testconsumer [1]: joining broker (rktp 0x261f260, 0 message(s) queued)
%7|1592858026.815|BRKMIGR|rdkafka#consumer-1| [thrd:main]: Migrating topic infrastructure.postmerge_tests.kafka.testconsumer [4] 0x2622800 from 10.137.150.246:9094/1 to 10.137.70.154:9094/2 (sending PARTITION_LEAVE to 10.137.150.246:9094/1)
%7|1592858026.815|FETCHADD|rdkafka#consumer-1| [thrd:10.137.13.66:9094/0]: 10.137.8.12:9094/0: Removed infrastructure.postmerge_tests.kafka.testconsumer [3] from fetch list (4 entries, opv 2): forced removal

...
%7|1592858374.785|HEARTBEAT|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/0: Heartbeat for group "infrastructure.postmerge_tests.kafka.testconsumer" generation id 11
%7|1592858374.790|HEARTBEAT|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" heartbeat error response in state up (join state started, 10 partition(s) assigned): Broker: Not coordinator
%7|1592858374.790|HEARTBEAT|rdkafka#consumer-1| [thrd:main]: Heartbeat failed due to coordinator (10.137.12.3:9094/0) no longer available: Broker: Not coordinator: re-querying for coordinator
%7|1592858374.790|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: 10.137.132.178:9094/1: Group "infrastructure.postmerge_tests.kafka.testconsumer": querying for coordinator: Broker: Not coordinator
%7|1592858374.813|CGRPCOORD|rdkafka#consumer-1| [thrd:main]: 10.137.132.178:9094/1: Group "infrastructure.postmerge_tests.kafka.testconsumer" coordinator is 10.137.12.3:9094 id 0
%7|1592858377.697|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op GET_ASSIGNMENT (v0) in state up (join state started, v4 vs 0)
%7|1592858377.747|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [0]: stored offset 3, committed offset 3: not including in commit
%7|1592858377.747|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [1]: stored offset 3, committed offset 3: not including in commit
%7|1592858377.747|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [2]: stored offset 3, committed offset 3: not including in commit
%7|1592858377.747|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [3]: stored offset 3, committed offset 3: not including in commit
%7|1592858377.747|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [4]: stored offset 3, committed offset 3: not including in commit
%7|1592858377.747|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [5]: stored offset 3, committed offset 3: not including in commit
%7|1592858377.747|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [6]: stored offset 6, committed offset 6: not including in commit
%7|1592858377.747|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [7]: stored offset -1001, committed offset -1001: not including in commit
%7|1592858377.747|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [8]: stored offset 3, committed offset 3: not including in commit
%7|1592858377.747|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [9]: stored offset 3, committed offset 3: not including in commit
%7|1592858377.747|COMMIT|rdkafka#consumer-1| [thrd:main]: OffsetCommit for 10 partition(s): cgrp auto commit timer: returned: Local: No offset stored
%7|1592858377.785|HEARTBEAT|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/0: Heartbeat for group "infrastructure.postmerge_tests.kafka.testconsumer" generation id 11
%7|1592858377.786|HEARTBEAT|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" heartbeat error response in state up (join state started, 10 partition(s) assigned): Broker: Not coordinator
%7|1592858377.786|HEARTBEAT|rdkafka#consumer-1| [thrd:main]: Heartbeat failed due to coordinator (10.137.12.3:9094/0) no longer available: Broker: Not coordinator: re-querying for coordinator
%7|1592858377.786|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: 10.137.132.178:9094/1: Group "infrastructure.postmerge_tests.kafka.testconsumer": querying for coordinator: Broker: Not coordinator
%7|1592858377.854|CGRPCOORD|rdkafka#consumer-1| [thrd:main]: 10.137.132.178:9094/1: Group "infrastructure.postmerge_tests.kafka.testconsumer" coordinator is 10.137.12.3:9094 id 0
%4|1592858379.285|SESSTMOUT|rdkafka#consumer-1| [thrd:main]: Consumer group session timed out (in join-state started) after 10499 ms without a successful response from the group coordinator (broker 0, last error was Broker: Not coordinator): revoking assignment and rejoining group
%7|1592858379.286|MEMBERID|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": updating member id "rdkafka-630bf2ad-18fb-4f69-bac7-37dd8ea27809" -> ""
%7|1592858379.286|REBALANCE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" is rebalancing in state up (join-state started) with assignment: Consumer group session timed out (in join-state started) after 10499 ms without a successful response from the group coordinator (broker 0, last error was Broker: Not coordinator)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Library pausing 10 partition(s)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [0]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v3
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [0] (v3)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [1]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v3
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [1] (v3)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [2]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v3
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [2] (v3)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [3]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v3
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [3] (v3)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [4]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v3
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [4] (v3)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [5]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v3
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [5] (v3)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [6]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v3
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [6] (v3)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [7]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v3
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [7] (v3)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [8]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v3
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [8] (v3)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [9]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v3
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [9] (v3)
%7|1592858379.286|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delegating revoke of 10 partition(s) to application rebalance callback on queue rd_kafka_cgrp_new: Consumer group session timed out (in join-state started) after 10499 ms without a successful response from the group coordinator (broker 0, last error was Broker: Not coordinator)
%7|1592858379.286|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state started -> wait-revoke-rebalance_cb (v4, state up)
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [0] received op PAUSE (v3) in fetch-state active (opv2)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [0]: at offset 3 (state active, v3)
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [1] received op PAUSE (v3) in fetch-state active (opv2)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [1]: at offset 3 (state active, v3)
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [2] received op PAUSE (v3) in fetch-state active (opv2)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [2]: at offset 3 (state active, v3)
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [3] received op PAUSE (v3) in fetch-state active (opv2)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [3]: at offset 3 (state active, v3)
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [4] received op PAUSE (v3) in fetch-state active (opv2)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [4]: at offset 3 (state active, v3)
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [5] received op PAUSE (v3) in fetch-state active (opv2)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [5]: at offset 3 (state active, v3)
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [6] received op PAUSE (v3) in fetch-state active (opv2)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [6]: at offset 6 (state active, v3)
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [7] received op PAUSE (v3) in fetch-state active (opv2)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [7]: at offset 0 (state active, v3)
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [8] received op PAUSE (v3) in fetch-state active (opv2)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [8]: at offset 3 (state active, v3)
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [9] received op PAUSE (v3) in fetch-state active (opv2)
%7|1592858379.286|PAUSE|rdkafka#consumer-1| [thrd:main]: Pause infrastructure.postmerge_tests.kafka.testconsumer [9]: at offset 3 (state active, v3)
%7|1592858379.286|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op ASSIGN (v0) in state up (join state wait-revoke-rebalance_cb, v4 vs 0)
%7|1592858379.286|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": new assignment of 0 partition(s) in join state wait-revoke-rebalance_cb
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": rd_kafka_cgrp_assign:2572: new version barrier v5
%7|1592858379.286|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state wait-revoke-rebalance_cb -> wait-unassign (v5, state up)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": rd_kafka_cgrp_unassign:2476: new version barrier v6
%7|1592858379.286|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": unassigning 10 partition(s) (v6)
%7|1592858379.286|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [0]: stored offset 3, committed offset 3: not including in commit
%7|1592858379.286|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [1]: stored offset 3, committed offset 3: not including in commit
%7|1592858379.286|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [2]: stored offset 3, committed offset 3: not including in commit
%7|1592858379.286|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [3]: stored offset 3, committed offset 3: not including in commit
%7|1592858379.286|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [4]: stored offset 3, committed offset 3: not including in commit
%7|1592858379.286|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [5]: stored offset 3, committed offset 3: not including in commit
%7|1592858379.286|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [6]: stored offset 6, committed offset 6: not including in commit
%7|1592858379.286|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [7]: stored offset -1001, committed offset -1001: not including in commit
%7|1592858379.286|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [8]: stored offset 3, committed offset 3: not including in commit
%7|1592858379.286|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic infrastructure.postmerge_tests.kafka.testconsumer [9]: stored offset 3, committed offset 3: not including in commit
%7|1592858379.286|COMMIT|rdkafka#consumer-1| [thrd:main]: OffsetCommit for 10 partition(s): unassign: returned: Local: No offset stored
%7|1592858379.286|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (0 wait_unassign, 10 assigned, 0 wait commit, join state wait-unassign): OffsetCommit done (__NO_OFFSET)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [0]: rd_kafka_toppar_op_fetch_stop:2334: new version barrier v4
%7|1592858379.286|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming infrastructure.postmerge_tests.kafka.testconsumer [0] (v4)
%7|1592858379.286|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic infrastructure.postmerge_tests.kafka.testconsumer [0]
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [1]: rd_kafka_toppar_op_fetch_stop:2334: new version barrier v4
%7|1592858379.286|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming infrastructure.postmerge_tests.kafka.testconsumer [1] (v4)
%7|1592858379.286|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic infrastructure.postmerge_tests.kafka.testconsumer [1]
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [2]: rd_kafka_toppar_op_fetch_stop:2334: new version barrier v4
%7|1592858379.286|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming infrastructure.postmerge_tests.kafka.testconsumer [2] (v4)
%7|1592858379.286|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic infrastructure.postmerge_tests.kafka.testconsumer [2]
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [3]: rd_kafka_toppar_op_fetch_stop:2334: new version barrier v4
%7|1592858379.286|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming infrastructure.postmerge_tests.kafka.testconsumer [3] (v4)
%7|1592858379.286|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic infrastructure.postmerge_tests.kafka.testconsumer [3]
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [4]: rd_kafka_toppar_op_fetch_stop:2334: new version barrier v4
%7|1592858379.286|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming infrastructure.postmerge_tests.kafka.testconsumer [4] (v4)
%7|1592858379.286|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic infrastructure.postmerge_tests.kafka.testconsumer [4]
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [5]: rd_kafka_toppar_op_fetch_stop:2334: new version barrier v4
%7|1592858379.286|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming infrastructure.postmerge_tests.kafka.testconsumer [5] (v4)
%7|1592858379.286|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic infrastructure.postmerge_tests.kafka.testconsumer [5]
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [6]: rd_kafka_toppar_op_fetch_stop:2334: new version barrier v4
%7|1592858379.286|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming infrastructure.postmerge_tests.kafka.testconsumer [6] (v4)
%7|1592858379.286|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic infrastructure.postmerge_tests.kafka.testconsumer [6]
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [7]: rd_kafka_toppar_op_fetch_stop:2334: new version barrier v4
%7|1592858379.286|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming infrastructure.postmerge_tests.kafka.testconsumer [7] (v4)
%7|1592858379.286|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic infrastructure.postmerge_tests.kafka.testconsumer [7]
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [8]: rd_kafka_toppar_op_fetch_stop:2334: new version barrier v4
%7|1592858379.286|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming infrastructure.postmerge_tests.kafka.testconsumer [8] (v4)
%7|1592858379.286|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic infrastructure.postmerge_tests.kafka.testconsumer [8]
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [9]: rd_kafka_toppar_op_fetch_stop:2334: new version barrier v4
%7|1592858379.286|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming infrastructure.postmerge_tests.kafka.testconsumer [9] (v4)
%7|1592858379.286|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic infrastructure.postmerge_tests.kafka.testconsumer [9]
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Library resuming 10 partition(s)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [0]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v5
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Resume infrastructure.postmerge_tests.kafka.testconsumer [0] (v5)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [1]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v5
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Resume infrastructure.postmerge_tests.kafka.testconsumer [1] (v5)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [2]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v5
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Resume infrastructure.postmerge_tests.kafka.testconsumer [2] (v5)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [3]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v5
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Resume infrastructure.postmerge_tests.kafka.testconsumer [3] (v5)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [4]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v5
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Resume infrastructure.postmerge_tests.kafka.testconsumer [4] (v5)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [5]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v5
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Resume infrastructure.postmerge_tests.kafka.testconsumer [5] (v5)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [6]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v5
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Resume infrastructure.postmerge_tests.kafka.testconsumer [6] (v5)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [7]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v5
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Resume infrastructure.postmerge_tests.kafka.testconsumer [7] (v5)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [8]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v5
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Resume infrastructure.postmerge_tests.kafka.testconsumer [8] (v5)
%7|1592858379.286|BARRIER|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [9]: rd_kafka_toppar_op_pause_resume:2393: new version barrier v5
%7|1592858379.286|RESUME|rdkafka#consumer-1| [thrd:main]: Resume infrastructure.postmerge_tests.kafka.testconsumer [9] (v5)
%7|1592858379.286|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (10 wait_unassign, 10 assigned, 0 wait commit, join state wait-unassign): unassign
%7|1592858379.286|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": assigning 0 partition(s) in join state wait-unassign
%7|1592858379.286|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [0] received op FETCH_STOP (v4) in fetch-state active (opv3)
%7|1592858379.286|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for infrastructure.postmerge_tests.kafka.testconsumer [0] in state active (v4)
%7|1592858379.286|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [0] changed fetch state active -> stopping
%7|1592858379.286|STORETERM|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [0]: offset store terminating
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [0] changed fetch state stopping -> stopped
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [1] received op FETCH_STOP (v4) in fetch-state active (opv3)
%7|1592858379.287|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for infrastructure.postmerge_tests.kafka.testconsumer [1] in state active (v4)
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [1] changed fetch state active -> stopping
%7|1592858379.287|STORETERM|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [1]: offset store terminating
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [1] changed fetch state stopping -> stopped
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [2] received op FETCH_STOP (v4) in fetch-state active (opv3)
%7|1592858379.287|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for infrastructure.postmerge_tests.kafka.testconsumer [2] in state active (v4)
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [2] changed fetch state active -> stopping
%7|1592858379.287|STORETERM|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [2]: offset store terminating
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [2] changed fetch state stopping -> stopped
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [3] received op FETCH_STOP (v4) in fetch-state active (opv3)
%7|1592858379.287|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for infrastructure.postmerge_tests.kafka.testconsumer [3] in state active (v4)
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [3] changed fetch state active -> stopping
%7|1592858379.287|STORETERM|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [3]: offset store terminating
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [3] changed fetch state stopping -> stopped
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [4] received op FETCH_STOP (v4) in fetch-state active (opv3)
%7|1592858379.287|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for infrastructure.postmerge_tests.kafka.testconsumer [4] in state active (v4)
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [4] changed fetch state active -> stopping
%7|1592858379.287|STORETERM|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [4]: offset store terminating
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [4] changed fetch state stopping -> stopped
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [5] received op FETCH_STOP (v4) in fetch-state active (opv3)
%7|1592858379.287|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for infrastructure.postmerge_tests.kafka.testconsumer [5] in state active (v4)
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [5] changed fetch state active -> stopping
%7|1592858379.287|STORETERM|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [5]: offset store terminating
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [5] changed fetch state stopping -> stopped
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [6] received op FETCH_STOP (v4) in fetch-state active (opv3)
%7|1592858379.287|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for infrastructure.postmerge_tests.kafka.testconsumer [6] in state active (v4)
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [6] changed fetch state active -> stopping
%7|1592858379.287|STORETERM|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [6]: offset store terminating
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [6] changed fetch state stopping -> stopped
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [7] received op FETCH_STOP (v4) in fetch-state active (opv3)
%7|1592858379.287|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for infrastructure.postmerge_tests.kafka.testconsumer [7] in state active (v4)
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [7] changed fetch state active -> stopping
%7|1592858379.287|STORETERM|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [7]: offset store terminating
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [7] changed fetch state stopping -> stopped
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [8] received op FETCH_STOP (v4) in fetch-state active (opv3)
%7|1592858379.287|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for infrastructure.postmerge_tests.kafka.testconsumer [8] in state active (v4)
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [8] changed fetch state active -> stopping
%7|1592858379.287|STORETERM|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [8]: offset store terminating
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [8] changed fetch state stopping -> stopped
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [9] received op FETCH_STOP (v4) in fetch-state active (opv3)
%7|1592858379.287|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for infrastructure.postmerge_tests.kafka.testconsumer [9] in state active (v4)
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [9] changed fetch state active -> stopping
%7|1592858379.287|STORETERM|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [9]: offset store terminating
%7|1592858379.287|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition infrastructure.postmerge_tests.kafka.testconsumer [9] changed fetch state stopping -> stopped
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [0] received op PAUSE (v5) in fetch-state stopped (opv4)
%7|1592858379.287|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped infrastructure.postmerge_tests.kafka.testconsumer [0]: at offset 3 (state stopped, v5)
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [1] received op PAUSE (v5) in fetch-state stopped (opv4)
%7|1592858379.287|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped infrastructure.postmerge_tests.kafka.testconsumer [1]: at offset 3 (state stopped, v5)
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [2] received op PAUSE (v5) in fetch-state stopped (opv4)
%7|1592858379.287|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped infrastructure.postmerge_tests.kafka.testconsumer [2]: at offset 3 (state stopped, v5)
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [3] received op PAUSE (v5) in fetch-state stopped (opv4)
%7|1592858379.287|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped infrastructure.postmerge_tests.kafka.testconsumer [3]: at offset 3 (state stopped, v5)
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [4] received op PAUSE (v5) in fetch-state stopped (opv4)
%7|1592858379.287|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped infrastructure.postmerge_tests.kafka.testconsumer [4]: at offset 3 (state stopped, v5)
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [5] received op PAUSE (v5) in fetch-state stopped (opv4)
%7|1592858379.287|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped infrastructure.postmerge_tests.kafka.testconsumer [5]: at offset 3 (state stopped, v5)
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [6] received op PAUSE (v5) in fetch-state stopped (opv4)
%7|1592858379.287|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped infrastructure.postmerge_tests.kafka.testconsumer [6]: at offset 6 (state stopped, v5)
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [7] received op PAUSE (v5) in fetch-state stopped (opv4)
%7|1592858379.287|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped infrastructure.postmerge_tests.kafka.testconsumer [7]: at offset 0 (state stopped, v5)
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [8] received op PAUSE (v5) in fetch-state stopped (opv4)
%7|1592858379.287|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped infrastructure.postmerge_tests.kafka.testconsumer [8]: at offset 3 (state stopped, v5)
%7|1592858379.287|OP|rdkafka#consumer-1| [thrd:main]: infrastructure.postmerge_tests.kafka.testconsumer [9] received op PAUSE (v5) in fetch-state stopped (opv4)
%7|1592858379.287|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped infrastructure.postmerge_tests.kafka.testconsumer [9]: at offset 3 (state stopped, v5)
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [0]
%7|1592858379.287|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delete infrastructure.postmerge_tests.kafka.testconsumer [0]
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [0]
%7|1592858379.287|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (9 wait_unassign, 9 assigned, 0 wait commit, join state wait-unassign): FETCH_STOP done
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [1]
%7|1592858379.287|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delete infrastructure.postmerge_tests.kafka.testconsumer [1]
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [1]
%7|1592858379.287|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (8 wait_unassign, 8 assigned, 0 wait commit, join state wait-unassign): FETCH_STOP done
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [2]
%7|1592858379.287|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delete infrastructure.postmerge_tests.kafka.testconsumer [2]
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [2]
%7|1592858379.287|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (7 wait_unassign, 7 assigned, 0 wait commit, join state wait-unassign): FETCH_STOP done
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [3]
%7|1592858379.287|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delete infrastructure.postmerge_tests.kafka.testconsumer [3]
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [3]
%7|1592858379.287|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (6 wait_unassign, 6 assigned, 0 wait commit, join state wait-unassign): FETCH_STOP done
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [4]
%7|1592858379.287|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delete infrastructure.postmerge_tests.kafka.testconsumer [4]
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [4]
%7|1592858379.287|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (5 wait_unassign, 5 assigned, 0 wait commit, join state wait-unassign): FETCH_STOP done
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [5]
%7|1592858379.287|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delete infrastructure.postmerge_tests.kafka.testconsumer [5]
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [5]
%7|1592858379.287|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (4 wait_unassign, 4 assigned, 0 wait commit, join state wait-unassign): FETCH_STOP done
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [6]
%7|1592858379.287|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delete infrastructure.postmerge_tests.kafka.testconsumer [6]
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [6]
%7|1592858379.287|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (3 wait_unassign, 3 assigned, 0 wait commit, join state wait-unassign): FETCH_STOP done
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [7]
%7|1592858379.287|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delete infrastructure.postmerge_tests.kafka.testconsumer [7]
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [7]
%7|1592858379.287|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (2 wait_unassign, 2 assigned, 0 wait commit, join state wait-unassign): FETCH_STOP done
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [8]
%7|1592858379.287|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delete infrastructure.postmerge_tests.kafka.testconsumer [8]
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [8]
%7|1592858379.287|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (1 wait_unassign, 1 assigned, 0 wait commit, join state wait-unassign): FETCH_STOP done
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [9]
%7|1592858379.287|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": delete infrastructure.postmerge_tests.kafka.testconsumer [9]
%7|1592858379.287|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for infrastructure.postmerge_tests.kafka.testconsumer [9]
%7|1592858379.287|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": unassign done in state up (join state wait-unassign): without new assignment: FETCH_STOP done
%7|1592858379.287|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state wait-unassign -> init (v6, state up)
%7|1592858379.287|JOIN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": join with 1 (1) subscribed topic(s)
%7|1592858379.287|CGRPMETADATA|rdkafka#consumer-1| [thrd:main]: consumer join: metadata for subscription is up to date (90024ms old)
%7|1592858379.287|JOIN|rdkafka#consumer-1| [thrd:main]: 10.137.12.3:9094/0: Joining group "infrastructure.postmerge_tests.kafka.testconsumer" with 1 subscribed topic(s)
%7|1592858379.287|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state init -> wait-join (v6, state up)
%7|1592858379.288|JOINGROUP|rdkafka#consumer-1| [thrd:main]: JoinGroup response: GenerationId -1, Protocol , LeaderId  (me), my MemberId , 0 members in group: Broker: Not coordinator
%7|1592858379.288|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state wait-join -> init (v6, state up)
%7|1592858379.288|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op COORD_QUERY (v0) in state up (join state init, v6 vs 0)
%7|1592858379.288|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: 10.137.70.154:9094/2: Group "infrastructure.postmerge_tests.kafka.testconsumer": querying for coordinator: Broker: Not coordinator
%7|1592858379.288|FETCHADD|rdkafka#consumer-1| [thrd:10.137.91.181:9094/2]: 10.137.70.154:9094/2: Removed infrastructure.postmerge_tests.kafka.testconsumer [0] from fetch list (5 entries, opv 2): not in active fetch state
%7|1592858379.288|FETCHADD|rdkafka#consumer-1| [thrd:10.137.91.181:9094/2]: 10.137.70.154:9094/2: Removed infrastructure.postmerge_tests.kafka.testconsumer [3] from fetch list (4 entries, opv 2): not in active fetch state
%7|1592858379.288|FETCHADD|rdkafka#consumer-1| [thrd:10.137.91.181:9094/2]: 10.137.70.154:9094/2: Removed infrastructure.postmerge_tests.kafka.testconsumer [6] from fetch list (3 entries, opv 2): not in active fetch state
%7|1592858379.288|FETCHADD|rdkafka#consumer-1| [thrd:10.137.91.181:9094/2]: 10.137.70.154:9094/2: Removed infrastructure.postmerge_tests.kafka.testconsumer [9] from fetch list (2 entries, opv 2): not in active fetch state
%7|1592858379.288|FETCHADD|rdkafka#consumer-1| [thrd:10.137.91.181:9094/2]: 10.137.70.154:9094/2: Removed infrastructure.postmerge_tests.kafka.testconsumer [2] from fetch list (1 entries, opv 2): not in active fetch state
%7|1592858379.288|FETCHADD|rdkafka#consumer-1| [thrd:10.137.91.181:9094/2]: 10.137.70.154:9094/2: Removed infrastructure.postmerge_tests.kafka.testconsumer [8] from fetch list (0 entries, opv 2): not in active fetch state
%7|1592858379.291|FETCHADD|rdkafka#consumer-1| [thrd:10.137.148.17:9094/1]: 10.137.132.178:9094/1: Removed infrastructure.postmerge_tests.kafka.testconsumer [1] from fetch list (3 entries, opv 2): not in active fetch state
%7|1592858379.291|FETCHADD|rdkafka#consumer-1| [thrd:10.137.148.17:9094/1]: 10.137.132.178:9094/1: Removed infrastructure.postmerge_tests.kafka.testconsumer [4] from fetch list (2 entries, opv 2): not in active fetch state
%7|1592858379.291|FETCHADD|rdkafka#consumer-1| [thrd:10.137.148.17:9094/1]: 10.137.132.178:9094/1: Removed infrastructure.postmerge_tests.kafka.testconsumer [7] from fetch list (1 entries, opv 2): not in active fetch state
%7|1592858379.291|FETCHADD|rdkafka#consumer-1| [thrd:10.137.148.17:9094/1]: 10.137.132.178:9094/1: Removed infrastructure.postmerge_tests.kafka.testconsumer [5] from fetch list (0 entries, opv 2): not in active fetch state
%7|1592858379.323|CGRPCOORD|rdkafka#consumer-1| [thrd:main]: 10.137.70.154:9094/2: Group "infrastructure.postmerge_tests.kafka.testconsumer" coordinator is 10.137.12.3:9094 id 0
%7|1592858381.753|JOIN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": join with 1 (1) subscribed topic(s)
%7|1592858381.753|CGRPMETADATA|rdkafka#consumer-1| [thrd:main]: consumer join: metadata for subscription is up to date (92490ms old)
%7|1592858381.753|JOIN|rdkafka#consumer-1| [thrd:main]: 10.137.12.3:9094/0: Joining group "infrastructure.postmerge_tests.kafka.testconsumer" with 1 subscribed topic(s)
%7|1592858381.753|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state init -> wait-join (v6, state up)
%7|1592858381.754|JOINGROUP|rdkafka#consumer-1| [thrd:main]: JoinGroup response: GenerationId -1, Protocol , LeaderId  (me), my MemberId , 0 members in group: Broker: Not coordinator
%7|1592858381.754|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state wait-join -> init (v6, state up)
%7|1592858381.754|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op COORD_QUERY (v0) in state up (join state init, v6 vs 0)
%7|1592858381.754|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: 10.137.132.178:9094/1: Group "infrastructure.postmerge_tests.kafka.testconsumer": querying for coordinator: Broker: Not coordinator
%7|1592858381.755|CGRPCOORD|rdkafka#consumer-1| [thrd:main]: 10.137.132.178:9094/1: Group "infrastructure.postmerge_tests.kafka.testconsumer" coordinator is 10.137.12.3:9094 id 0
%7|1592858382.697|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op GET_ASSIGNMENT (v0) in state up (join state init, v6 vs 0)
%7|1592858382.747|COMMIT|rdkafka#consumer-1| [thrd:main]: OffsetCommit for -1 partition(s): cgrp auto commit timer: returned: Local: No offset stored
%7|1592858382.747|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": unassign done in state up (join state init): without new assignment: OffsetCommit done (__NO_OFFSET)
%7|1592858383.753|JOIN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": join with 1 (1) subscribed topic(s)
%7|1592858383.753|CGRPMETADATA|rdkafka#consumer-1| [thrd:main]: consumer join: metadata for subscription is up to date (94490ms old)
%7|1592858383.753|JOIN|rdkafka#consumer-1| [thrd:main]: 10.137.12.3:9094/0: Joining group "infrastructure.postmerge_tests.kafka.testconsumer" with 1 subscribed topic(s)
%7|1592858383.753|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state init -> wait-join (v6, state up)
%7|1592858383.754|JOINGROUP|rdkafka#consumer-1| [thrd:main]: JoinGroup response: GenerationId -1, Protocol , LeaderId  (me), my MemberId , 0 members in group: Broker: Not coordinator
%7|1592858383.754|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state wait-join -> init (v6, state up)
%7|1592858383.754|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op COORD_QUERY (v0) in state up (join state init, v6 vs 0)
%7|1592858383.754|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: 10.137.132.178:9094/1: Group "infrastructure.postmerge_tests.kafka.testconsumer": querying for coordinator: Broker: Not coordinator
%7|1592858383.755|CGRPCOORD|rdkafka#consumer-1| [thrd:main]: 10.137.132.178:9094/1: Group "infrastructure.postmerge_tests.kafka.testconsumer" coordinator is 10.137.12.3:9094 id 0
%7|1592858385.753|JOIN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": join with 1 (1) subscribed topic(s)
%7|1592858385.753|CGRPMETADATA|rdkafka#consumer-1| [thrd:main]: consumer join: metadata for subscription is up to date (96490ms old)
%7|1592858385.753|JOIN|rdkafka#consumer-1| [thrd:main]: 10.137.12.3:9094/0: Joining group "infrastructure.postmerge_tests.kafka.testconsumer" with 1 subscribed topic(s)
%7|1592858385.753|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state init -> wait-join (v6, state up)
%7|1592858385.754|JOINGROUP|rdkafka#consumer-1| [thrd:main]: JoinGroup response: GenerationId -1, Protocol , LeaderId  (me), my MemberId , 0 members in group: Broker: Not coordinator
%7|1592858385.754|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" changed join state wait-join -> init (v6, state up)
%7|1592858385.754|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op COORD_QUERY (v0) in state up (join state init, v6 vs 0)
%7|1592858385.754|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: 10.137.70.154:9094/2: Group "infrastructure.postmerge_tests.kafka.testconsumer": querying for coordinator: Broker: Not coordinator
%7|1592858385.755|CGRPCOORD|rdkafka#consumer-1| [thrd:main]: 10.137.70.154:9094/2: Group "infrastructure.postmerge_tests.kafka.testconsumer" coordinator is 10.137.12.3:9094 id 0
%7|1592858387.697|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer" received op GET_ASSIGNMENT (v0) in state up (join state init, v6 vs 0)
%7|1592858387.747|COMMIT|rdkafka#consumer-1| [thrd:main]: OffsetCommit for -1 partition(s): cgrp auto commit timer: returned: Local: No offset stored
%7|1592858387.747|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Group "infrastructure.postmerge_tests.kafka.testconsumer": unassign done in state up (join state init): without new assignment: OffsetCommit done (__NO_OFFSET)

< stuck at this point already, last lines repeated many times > 

```

</details>

 - [ ] Provide broker log excerpts -- happy to provide these although I'm unclear what to look for
 - [ ] Critical issue: this was a major issue for us but the revert reduced the urgency. It does seem quite important and likely but the lack of other reports makes me wonder if we are doing something incorrect

### PR DESCRIPTION
**Pull request by ajbarb**
Resolves #2944

### CODE REVIEW

**Comment by edenhill** [comment]
Is this fix really verified? forceResetAddress does not seem to be used in the resolve function.

I think a simpler approach is simply to reset rkb_ts_rsal_last to 0.

**Comment by ajbarb** [comment]
> Is this fix really verified? forceResetAddress does not seem to be used in the resolve function.
> 
> I think a simpler approach is simply to reset rkb_ts_rsal_last to 0.

I missed to move a change. I updated the PR and yeah the change is verified. My worry with setting rkb_ts_rsal_last to zero is that it depends on an user config broker_addr_ttl and also how rd_clock is implemented.

File: src/rdkafka_broker.c [hunk 1]
```diff
@@ -923,7 +923,8 @@ rd_kafka_broker_send (rd_kafka_broker_t *rkb, rd_slice_t *slice) {
 
 
 static int rd_kafka_broker_resolve (rd_kafka_broker_t *rkb,
-                                    const char *nodename) {
+                                    const char *nodename,
+                                    rd_bool_t forceResetAddress) {
```
Comment (edenhill) [inline src/rdkafka_broker.c:927]: We typically use snake_case in the code, so rename this to `reset_cached_addr`.

Comment (ajbarb) [reply src/rdkafka_broker.c]: Updated it. Thansk!

**Review by edenhill — APPROVED** [review]
LGTM! Thanks for your contribution
