### PR TITLE
Include error message in CreatePartitions result

### LINKED ISSUE #2154: Missing broker message upon create partitions error
Description
===========
If an error occurs while handling a create partitions request, the broker returns an error message.  See the `error_message` field in CreatePartitionsResponse. Currently librdkafka does not expose this message but instead always returns the default message for the error code.

How to reproduce
================
- Call `rd_kafka_CreatePartitions()` with invalid arguments. For example specifying a new partition count less or equals to current count.

- Call `rd_kafka_topic_result_error_string()` and get the default message instead of the custom message from the broker.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): ` fa71cce`
 - [X] Apache Kafka version: `>1.0.0`
 - [X] librdkafka client configuration: `default`
 - [X] Operating system: `all`

### PR DESCRIPTION
**Pull request by mimaison**
fixes #2154

Co-authored-by: Mickael Maison <mickael.maison@gmail.com>
Co-authored-by: Edoardo Comar <ecomar@uk.ibm.com>

### CODE REVIEW

File: src/rdkafka_admin.c [hunk 1]
```diff
@@ -1750,15 +1750,14 @@ rd_kafka_CreatePartitionsResponse_parse (rd_kafka_op_t *rko_req,
                                 errstr = (char *)rd_kafka_err2str(error_code);
                         else
                                 RD_KAFKAP_STR_DUPA(&errstr, &error_msg);
+                } else {
+                        errstr = NULL;
```
Comment (edenhill) [inline src/rdkafka_admin.c]: errstr is the parent's buffer, which might be needed later in this function, so suggest not setting it to NULL here.
Instead change the result_new(..) call below to `error_code ? errstr : NULL`

**Comment by edenhill** [comment]
Thank you for this!
